config/routes.rb
EySample::Application.routes.draw do

  root 'home#index'
  get 'home/add_ons' => 'home#add_ons'
  post '/mail' => 'home#mail'
  get '/mail_list' => 'home#mail_list'
  get '/admin' => 'application#admin'
  resources :comments

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/mongo/access.rb
class Access
  @@coll = $mongo_db[self.name.underscore.pluralize]

  def self.set(request)
    @@coll.insert({remote_host: request.env['REMOTE_HOST'], created_at: Time.now})
  end

  def self.tail
    @@coll.find({}, {:limit => 20, :sort => ['created_at', Mongo::DESCENDING]})
  end

  def self.count
    @@coll.count rescue 0
  end
end

app/models/mongo/mail.rb
class Mail
  @@coll = $mongo_db[self.name.underscore.pluralize]

  def self.set(body)
    @@coll.insert({body: body, created_at: Time.now})
  end

  def self.tail
    @@coll.find({}, {:limit => 20, :sort => ['created_at', Mongo::DESCENDING]})
  end

  def self.count
    @@coll.count rescue 0
  end
end

app/controllers/application_controller.rb
require 'socket'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def admin
    render text: Socket.gethostname
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params[:comment].permit(:text)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:mail]
  def index
  end

  def add_ons
    @access_tail = Access.tail
    @access_count = Access.count
  end

  def mail
    Mail.set(params)
    render :text => 'ok', :status => 200
  end

  def mail_list
    @mail_list = Mail.tail
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def clc_image_tag(name)
    case Rails.env
    when 'production', 'staging'
      cl_image_tag('sample.png')
    else
      'only production'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/_form.html.haml
= form_for @comment do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  = f.text_field :text 
  .actions
    = f.submit 'Save'

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %tr
    %th
    %th
    %th
    %th

  - @comments.each do |comment|
    %tr
      %td= comment.text
      %td= link_to 'Show', comment
      %td= link_to 'Edit', edit_comment_path(comment)
      %td= link_to 'Destroy', comment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path

app/views/home/add_ons.html.haml
.hero-unit
  %h2 Newrelic
  :erb
    <iframe src="https://rpm.newrelic.com/public/charts/hsHBWlinvL" width="725" height="425" scrolling="no" frameborder="no"></iframe>
.hero-unit
  %h2 MongoHQ
  %ol
    - @access_tail.each do |access|
      %li
        = access['remote_host']
        \:
        = access['created_at']
  %h3
    Total:
    = @access_count

app/views/home/index.html.haml
.hero-unit
  %p 開発にリソースを集中
  %p Proactive Support
  %p スケール
  %p セキュリティ
  %p ssh & sudo & Support
  %p 24H * 365days 有人監視

.hero-unit
  %p PHP
  %p Ruby on Rails, Rack App
  %p Node.js
  %p Add-Ons
  %p Chef
  %p AWS

.hero-unit
  %p Github
  %p Groupon
  %p cerego(iKnow)
  %p Mediwave
  %p Newrelic
  %p Facebook

app/views/home/mail_list.html.haml
- @mail_list.each do |mail|
  - body = mail['body']
  - ["From", "FromFull", "To", "ToFull", "Cc", "CcFull", "ReplyTo", "Subject", "MessageID", "Date", "MailboxHash", "TextBody", "HtmlBody", "Tag", "Headers", "Attachments"].each do |key|
    %p
      %span= key
      = body[key] || '--'
  %hr

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "EySample"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'


  %body
    .container
      .row
        .span9
          %h1= link_to 'EngineYard Sample App', '/'
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            = image_tag 'ey_logo.jpeg', :width => '100px'
            %p
              %span The Leading Platform as a Service
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "EngineYard Site", "http://www.engineyard.co.jp/"
              %li= link_to "EngineYard Cloud Dashboard", "https://cloud.engineyard.com/"
            %ul.nav.nav-list
              %li.nav-header Add-Ons
              %li= link_to 'All', home_add_ons_path
              %li= link_to 'NewRelic', home_add_ons_path
          .well.sidebar-nav
            %li.nav-header Twitter
            :erb
              <a class="twitter-timeline" href="https://twitter.com/search?q=engine+yard" data-widget-id="346856096406843393">engine yard に関するツイート</a>
              <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

    
      %footer
        %p &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"